server:
  port: 8080
spring:
  application:
    name: zuul-server

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://52.62.128.221:8761/eureka

zuul:
  sensitiveHeaders: Cookie,Set-Cookie

ribbon:
  ReadTimeout: 19000
  ConnectTimeout: 19000


#security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:8080/auth-server/oauth/token
#      user-authorization-uri: http://localhost:8080/auth-server/oauth/authorize
#      client-id: client
#      client-secret: secret



